limit_req_zone $binary_remote_addr zone=signup_sms:10m rate=1r/m;

server {
    listen 80;
    server_name quickpick.lukasbreuer.de;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name quickpick.lukasbreuer.de;
    ssl_certificate /etc/letsencrypt/live/quickpick.lukasbreuer.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/quickpick.lukasbreuer.de/privkey.pem;

    location /v1/signup/request/code/ {
        limit_req zone=signup_sms;
        limit_req_status 429;

        proxy_pass http://core:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://core:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}